/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/BlenderObject.glb 
*/

import { useContext } from "react";
import { ThemeContext } from "./App";
import { useState, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  // Getting context from App
  const { mouseCords, setMouseCords } = useContext(ThemeContext);
  const { nodes, materials } = useGLTF("/BlenderObject.glb");

  const [monitorImg, setMonitorImg] = useState("/test.jpg");
  const monitorRef = useRef();

  const monitorTexture = useTexture(monitorImg);
  monitorTexture.flipY = false;

  // Make computer face the mouse
  useFrame((state, delta) => {
    monitorRef.current.rotation.y =
      mouseCords.clientX / window.innerWidth - 0.5;
    monitorRef.current.rotation.x =
      mouseCords.clientY / window.innerHeight - 0.5;
    monitorRef.current.position.x =
      (mouseCords.clientX / window.innerWidth - 0.5);
    monitorRef.current.position.y =
      (mouseCords.clientY / window.innerHeight - 0.5);
  });

  return (
    <group {...props} dispose={null} ref={monitorRef}>
      <group position={[0, -0.002, 0.082]} scale={[1.755, 1.142, 1.83]}>
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials["inner-computer-case"]}
        />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <mesh
        geometry={nodes.Monitor.geometry}
        material={nodes.Monitor.material}
        position={[-0.387, -0.012, 1.765]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.113, 0.802, 0.802]}
      >
        <meshStandardMaterial map={monitorTexture} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/BlenderObject.glb");
